version: '3.8'

services:
    mevo_transactions:
        build:
            dockerfile: Dockerfile
        container_name: mevo_transactions
        env_file:
            - .env
        ports:
            - '${PORT:-9095}:9095'
        volumes:
            - ./:/usr/src/app
        depends_on:
            - mongodb
        command: sh -c "npm install && npm run build && npm start"
        restart: unless-stopped

    mongodb:
        image: mongo:latest
        container_name: mevo_mongo
        restart: always
        env_file:
            - '.env'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_AUTH}
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        external: false
