version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mevo_mongo
        restart: always
        ports:
            - '27017:27017'
        env_file:
            - '../.env'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_AUTH}
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        external: false
